# Generated by Django 4.1.3 on 2022-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_answered",
            field=models.BooleanField(default=False),
        ),
    ]
