# Generated by Django 4.1.3 on 2022-11-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_ticket_ticket_answered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_answered",
        ),
    ]
