# Generated by Django 4.1.3 on 2022-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_remove_ticket_ticket_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="answered",
            field=models.BooleanField(default=False),
        ),
    ]
